# Generated by Django 3.0.7 on 2024-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='breed',
            field=models.CharField(default='british', max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('animal', 'Animal'), ('plant', 'Plant')], default='animal', max_length=6),
        ),
    ]
