# Generated by Django 3.0.7 on 2024-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20240314_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('animal', 'Animal'), ('plant', 'Plant')], default='plant', max_length=6),
        ),
    ]
